/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biometric;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author tharindu
 */
public class login extends javax.swing.JFrame {
    
    DateFormat dateFormat = new SimpleDateFormat("HH:mm:ss");
    ArrayList<Object> presslist = new ArrayList<Object>();
    ArrayList<Object> releaselist = new ArrayList<Object>();
    ArrayList<user> userlist = new ArrayList<user>();
    ArrayList<Object> mean = new ArrayList<Object>();

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
//        user u1=new user("Tharindu", (float) 120.92308);
//        user u2=new user("Mahesh",(float)109.051285);
//        user u3=new user("Mahesh",9495);
//        user u4=new user("Madushan",10495);
//        user u5=new user("Lashan",11495);
//        userlist.add(u1);
//        userlist.add(u2);
//        userlist.add(u3);
//        userlist.add(u4);
//        userlist.add(u5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        loginTxt = new javax.swing.JTextField();
        loginBtn = new javax.swing.JButton();
        tryAgainBtn = new javax.swing.JButton();
        signupBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("LOGIN");

        jLabel3.setText("\"the curves of your lips rewrite history\"");

        jLabel4.setText("enter above phrase");

        loginTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                loginTxtKeyReleased(evt);
            }
        });

        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        tryAgainBtn.setText("TryAgain");
        tryAgainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tryAgainBtnActionPerformed(evt);
            }
        });

        signupBtn.setText("SignUp");
        signupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(loginTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(tryAgainBtn)
                        .addGap(48, 48, 48)
                        .addComponent(loginBtn)
                        .addGap(39, 39, 39)
                        .addComponent(signupBtn)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addGap(29, 29, 29)
                .addComponent(loginTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginBtn)
                    .addComponent(tryAgainBtn)
                    .addComponent(signupBtn))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginTxtKeyPressed
        // TODO add your handling code here:
        Date d1 = new Date();
        long t = d1.getTime();
        presslist.add(t);
        
    }//GEN-LAST:event_loginTxtKeyPressed

    private void loginTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginTxtKeyReleased
        // TODO add your handling code here:
        Date d2 = new Date();
        long t = d2.getTime();
        releaselist.add(t);
    }//GEN-LAST:event_loginTxtKeyReleased

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        if ("the curves of your lips rewrite history".equals(loginTxt.getText())){
            sqliteConn scon=new sqliteConn();
            ResultSet res;
            userlist.clear();
            
            try{
                res=scon.displayUsers();
                while(res.next()){
                    user u=new user(res.getString("name"),(float)res.getDouble("phraseTime"));
                    userlist.add(u);
                }
            }catch(ClassNotFoundException e){
                System.out.println(e);
            }catch(SQLException e){
                System.out.println(e);
            }
            
            if(presslist.size()==releaselist.size()){
                for (int i =0; i<presslist.size();i++){
                    long m = (long)releaselist.get(i)-(long)presslist.get(i);
                    mean.add(m);
                }
                long total = 0;
                for (int i=0;i<mean.size();i++){
                    total+= (long)mean.get(i);
                }
                float ttl = total;
                float size= mean.size();
//                System.out.println(ttl);
//                System.out.println(size);
                float mn=ttl/size;
//                System.out.println(mn);

                int count=0;
                
                for (user u : userlist){
                    if(mn <= u.getPhaseTime()+2.5 && u.getPhaseTime()-2.5 <= mn){
                        JOptionPane.showMessageDialog(null, "Welcome "+u.getName());
                        break;
                    }
                    else{
                        System.out.println("Not match phrase time of user " + u.getName());
                        count++;
                    }
                }
                if(count==userlist.size()){
                    JOptionPane.showMessageDialog(null, "Your login is not matched with any users.");
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Your login prohibited! Your input pharse is incorrect");
            presslist.clear();
            releaselist.clear();
            mean.clear();
            loginTxt.setText("");
        }
        
    }//GEN-LAST:event_loginBtnActionPerformed

    private void tryAgainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tryAgainBtnActionPerformed
        // TODO add your handling code here:
        presslist.clear();
        releaselist.clear();
        mean.clear();
        loginTxt.setText("");
        
    }//GEN-LAST:event_tryAgainBtnActionPerformed

    private void signupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new signup().setVisible(true);
    }//GEN-LAST:event_signupBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JTextField loginTxt;
    private javax.swing.JButton signupBtn;
    private javax.swing.JButton tryAgainBtn;
    // End of variables declaration//GEN-END:variables
}
