/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biometric;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author tharindu
 */
public class signup extends javax.swing.JFrame {
    
    DateFormat dateFormat = new SimpleDateFormat("HH:mm:ss");
    ArrayList<Object> presslist = new ArrayList<Object>();
    ArrayList<Object> releaselist = new ArrayList<Object>();
    ArrayList<Object> mean = new ArrayList<Object>();

    /**
     * Creates new form signup
     */
    public signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usernameTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tryagainBtn = new javax.swing.JButton();
        signupBtn = new javax.swing.JButton();
        loginBtn = new javax.swing.JButton();
        pharseTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SIGNUP");

        jLabel2.setText("User Name");

        jLabel3.setText("To Identify Your Login Please Enter Below Pharse");

        jLabel4.setText("\"the curves of your lips rewrite history\"");

        tryagainBtn.setText("Try Again");
        tryagainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tryagainBtnActionPerformed(evt);
            }
        });

        signupBtn.setText("SignUp");
        signupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupBtnActionPerformed(evt);
            }
        });

        loginBtn.setText("LogIn");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        pharseTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pharseTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pharseTxtKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tryagainBtn)
                                .addGap(57, 57, 57)
                                .addComponent(signupBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(26, 26, 26)
                                .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pharseTxt)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(loginBtn)
                            .addComponent(jLabel3))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addGap(27, 27, 27)
                .addComponent(pharseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tryagainBtn)
                    .addComponent(signupBtn)
                    .addComponent(loginBtn))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupBtnActionPerformed
        // TODO add your handling code here:
        if(!"".equals(usernameTxt.getText())){
            if ("the curves of your lips rewrite history".equals(pharseTxt.getText())){
                sqliteConn scon=new sqliteConn();

                if(presslist.size()==releaselist.size()){
                    for (int i =0; i<presslist.size();i++){
                        long m = (long)releaselist.get(i)-(long)presslist.get(i);
                        mean.add(m);
                    }
                    long total = 0;
                    for (int i=0;i<mean.size();i++){
                        total+= (long)mean.get(i);
                    }
                    float ttl = total;
                    float size= mean.size();
//                    System.out.println(ttl);
//                    System.out.println(size);
                    float mn=ttl/size;
//                    System.out.println(mn);

                    try{
                        scon.addUser(usernameTxt.getText(), mn);
                        JOptionPane.showMessageDialog(null, "Your SignUp as " +usernameTxt.getText());
                    }catch(ClassNotFoundException e){
                        System.out.println(e);
                    }catch(SQLException e){
                        System.out.println(e);
                    }
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Your SignUp prohibited! Your input pharse is incorrect");
                presslist.clear();
                releaselist.clear();
                mean.clear();
                pharseTxt.setText("");
            }
        }else{
                JOptionPane.showMessageDialog(null, "Enter a Username");
            }
    }//GEN-LAST:event_signupBtnActionPerformed

    private void tryagainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tryagainBtnActionPerformed
        // TODO add your handling code here:
        presslist.clear();
        releaselist.clear();
        mean.clear();
        pharseTxt.setText("");
    }//GEN-LAST:event_tryagainBtnActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_loginBtnActionPerformed

    private void pharseTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pharseTxtKeyPressed
        // TODO add your handling code here:
        Date d1 = new Date();
        long t = d1.getTime();
        presslist.add(t);
    }//GEN-LAST:event_pharseTxtKeyPressed

    private void pharseTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pharseTxtKeyReleased
        // TODO add your handling code here:
        Date d2 = new Date();
        long t = d2.getTime();
        releaselist.add(t);
    }//GEN-LAST:event_pharseTxtKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton loginBtn;
    private javax.swing.JTextField pharseTxt;
    private javax.swing.JButton signupBtn;
    private javax.swing.JButton tryagainBtn;
    private javax.swing.JTextField usernameTxt;
    // End of variables declaration//GEN-END:variables
}
